#!/bin/bash

source ~/.secrets/credentials.sh

tmpfile=$(mktemp)
grim -g "$(slurp -d)" - > $tmpfile
gcloud \
  ml vision detect-text $tmpfile \
  --project="$GCP_PROJECT_FOR_VISION" \
  | jq -r  '.responses[].fullTextAnnotation.text' \
  | wl-copy
notify-send --expire-time 1500 "OCR copied to clipboard!"
