#!/usr/bin/env python3

import os
import tomllib
import subprocess
import json
from pathlib import Path
import sys

from typing import TypedDict

AEROSPACE_CONFIG = Path(os.environ["HOME"]) / ".config" / "aerospace" / "aerospace.toml"

Monitor = TypedDict("Monitor", {
    "monitor-id": int,
    "monitor-name": str,
})

Workspace = TypedDict("Workspace", {
    "monitor-id": int,
    "monitor-name": str,
    "workspace": str,
    "workspace-is-focused": bool,
    "workspace-is-visible": bool,
})

Window = TypedDict("Window", {
    "monitor-id": int,
    "monitor-name": str,
    "workspace": str,
    "workspace-is-focused": bool,
    "workspace-is-visible": bool,
    "app-name": str,
    "app-pid": int,
    "app-bundle-id": int,
    "window-is-fullscreen": bool,
    "window-id": int,
    "window-title": str,
})

def log(*, text: str, title: str = "Ctrl+Tab") -> None:
    run(["terminal-notifier", "-title", title, "-message", f"💬 {text}"])

def invert_dict(d):
    """
    Inverts a dictionary, with special handling for list values.
    Generated by claude-3.7
    
    For normal values:
        - Keys in the original dict become values in the inverted dict
        - Values in the original dict become keys in the inverted dict
    
    For list values:
        - Each element in the list becomes a separate key in the inverted dict
        - Each of these keys points to the original key
    
    Args:
        d (dict): The dictionary to invert
        
    Returns:
        dict: An inverted dictionary
    """
    inverted = {}
    
    for key, value in d.items():
        # Special handling for list values
        if isinstance(value, list):
            for item in value:
                # Handle unhashable items within the list
                if isinstance(item, (list, dict, set)):
                    hashable_item = str(item)
                else:
                    hashable_item = item
                
                # Add to inverted dict
                if hashable_item in inverted:
                    inverted[hashable_item].append(key)
                else:
                    inverted[hashable_item] = [key]
        else:
            # Handle regular values
            if isinstance(value, (dict, set)):
                # Convert unhashable values to strings
                hashable_value = str(value)
            else:
                hashable_value = value
                
            # Add to inverted dict
            if hashable_value in inverted:
                inverted[hashable_value].append(key)
            else:
                inverted[hashable_value] = [key]
            
    return inverted


def run(cmd) -> str:
    result = subprocess.run(
        cmd, capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"ERROR running {' '.join(cmd)}: {result.stderr}")
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    return result.stdout

def run_json(cmd) -> dict:
    result = subprocess.run(
        cmd + ["--json"], capture_output=True, text=True
    )
    if result.returncode != 0:
        print(f"ERROR running {' '.join(cmd)}: {result.stderr}")
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")
    if not result.stdout.strip():
        print(f"ERROR: No output from {' '.join(cmd)} --json")
        raise RuntimeError(f"No output from {' '.join(cmd)} --json")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as e:
        print(f"ERROR: Could not parse JSON output from {' '.join(cmd)} --json")
        print("Output was:", repr(result.stdout))
        raise

def get_workspace_to_monitor(config_path) -> dict:
    with config_path.open("rb") as f:
        data = tomllib.load(f)
    return data.get("workspace-to-monitor-force-assignment", {})

def get_plugged_monitors() -> list[Monitor]:
    return run_json(["aerospace", "list-monitors", "--format", r"%{monitor-id} %{monitor-name}"])

def get_windows() -> list[Window]:
    return run_json(["aerospace", "list-windows", "--all",  "--format", r"%{window-id} %{window-title} %{window-is-fullscreen} %{app-bundle-id} %{app-name} %{app-pid} %{workspace} %{workspace-is-focused} %{workspace-is-visible} %{monitor-id} %{monitor-name}"])

def get_focused_window() -> Window | None:
    try:
        return run_json(["aerospace", "list-windows", "--focused",  "--format", r"%{window-id} %{window-title} %{window-is-fullscreen} %{app-bundle-id} %{app-name} %{app-pid} %{workspace} %{workspace-is-focused} %{workspace-is-visible} %{monitor-id} %{monitor-name}"])[0]
    except Exception:
        return None

def get_workspaces() -> list[Workspace]:
    return run_json(["aerospace", "list-workspaces", "--all", "--format", r"%{workspace} %{workspace-is-focused} %{workspace-is-visible} %{monitor-id} %{monitor-name}"])

def compose_workspace_sequences(*, plugged_monitors: list[Monitor], workspaces: list[Workspace]) -> dict[int, list[Workspace]]:
    """
    Create a dict containing monitor_ids as keys, and lists of workspaces as values.
    These are the values of the workspaces that are bound to that given screen.
    """
    # Load assignments from config
    workspace_to_monitor = get_workspace_to_monitor(AEROSPACE_CONFIG)
    monitor_to_workspace = invert_dict(workspace_to_monitor)
    # Get all monitors
    monitor_groups: dict[int, list[Workspace]] = {}
    for monitor in plugged_monitors:
        monitor_id, monitor_name = monitor["monitor-id"], monitor["monitor-name"]
        # Convert monitor_id to string to match config format
        monitor_id_str = str(monitor_id)
        try:
            monitor_workspaces = [w for w  in workspaces if w["monitor-id"] == monitor_id and  w["workspace"] in monitor_to_workspace[monitor_id_str]]
        except KeyError as e:
            log(text=f"No workspace assignments for monitor {monitor_id} ({monitor_name})")
            continue
        # Get list of workspace names assigned to this monitor_id
        monitor_groups[monitor_id] = monitor_workspaces
    return monitor_groups

def cycle_workspace_group(move_focused: bool = False):
    plugged_monitors = get_plugged_monitors()
    workspaces = get_workspaces()

    monitor_id_to_workspace_sequence = compose_workspace_sequences(plugged_monitors=plugged_monitors, workspaces=workspaces)
    focused_window = get_focused_window()
    focused_window_target_workspace = None

    # Get the first available monitor's workspace count, or bail if none exist
    if not monitor_id_to_workspace_sequence:
        log(text="No monitor workspace sequences found", title="🐞 Ctrl+Tab")
        return

    amount_of_workpaces_in_monitor = len(next(iter(monitor_id_to_workspace_sequence.values())))

    # Use the first available monitor instead of assuming monitor-id=1 exists
    first_monitor_id = next(iter(monitor_id_to_workspace_sequence.keys()))

    # Find visible workspace on the first monitor
    try:
        first_monitor_visible_workspace = next(
            w for w in workspaces
            if w["monitor-id"] == first_monitor_id and w["workspace-is-visible"]
        )["workspace"]
    except StopIteration:
        log(text=f"No visible workspace found on monitor {first_monitor_id}", title="🐞 Ctrl+Tab")
        return

    first_monitor_workspace_sequence = [w["workspace"] for w in monitor_id_to_workspace_sequence[first_monitor_id]]
    try:
        index_in_first_monitor = first_monitor_workspace_sequence.index(first_monitor_visible_workspace)
    except ValueError:
        index_in_first_monitor = 0

    # Verify all monitors are at the same index position (synced)
    for monitor_id, workspace_list in monitor_id_to_workspace_sequence.items():
        visible_workspace = next(
            (w for w in workspaces if w["monitor-id"] == monitor_id and w["workspace-is-visible"]),
            None
        )
        if visible_workspace:
            workspace_sequence = [w["workspace"] for w in workspace_list]
            try:
                current_index = workspace_sequence.index(visible_workspace["workspace"])
                if current_index != index_in_first_monitor:
                    # Out of sync! Resync this monitor to match the first monitor's index
                    sync_workspace = workspace_sequence[index_in_first_monitor]
                    run(["aerospace", "workspace", sync_workspace])
            except (ValueError, IndexError):
                pass

    if index_in_first_monitor == amount_of_workpaces_in_monitor - 1:
        next_workspace_index = 0
    else:
        next_workspace_index = index_in_first_monitor + 1

    for monitor in plugged_monitors:
        monitor_id = monitor["monitor-id"]

        # Skip monitors that don't have workspace assignments
        if monitor_id not in monitor_id_to_workspace_sequence:
            continue

        workspace_sequence = [w["workspace"] for w in monitor_id_to_workspace_sequence[monitor["monitor-id"]] if w["monitor-id"] == monitor_id]

        # Skip if no workspaces found for this monitor
        if not workspace_sequence or next_workspace_index >= len(workspace_sequence):
            continue

        next_workspace = workspace_sequence[next_workspace_index]
        run(["aerospace", "workspace", next_workspace])

        if move_focused and focused_window and focused_window["monitor-id"] == monitor_id:
            focused_window_target_workspace = next_workspace

    if focused_window_target_workspace is not None:
        run(["aerospace", "move-node-to-workspace", "--focus-follows-window", "--window-id", str(focused_window["window-id"]), focused_window_target_workspace])


if __name__ == "__main__":

    move_focused = (len(sys.argv) > 1 and sys.argv[1] == "--move-focused")
    try:
        cycle_workspace_group(move_focused=move_focused)
    except Exception as e:
        log(text=f"Control+Tab failed. Error: {(str(e))} (type: {type(e).__name__}).", title="🐞 Ctrl+Tab")
