#!/bin/bash

args=("$@")

edp1_ws="Pro Perso"
dp1_ws="Pro-1 Perso-1"
dp2_ws="Pro-2 Perso-2"
dp3_ws="Pro-3 Perso-3"
dp4_ws="Pro-4 Perso-4"
dp5_ws="Pro-5 Perso-5"

declare -A OUTPUTS

OUTPUTS[eDP-1]="${edp1_ws}"
OUTPUTS[DP-1]="${dp1_ws}"
OUTPUTS[DP-2]="${dp2_ws}"
OUTPUTS[DP-3]="${dp3_ws}"
OUTPUTS[DP-4]="${dp4_ws}"
OUTPUTS[DP-5]="${dp5_ws}"

CURRENT_OUTPUTS=( $(i3-msg -t get_outputs | jq -r '.[] | select(.active) | .name') )
FOCUSED_OUTPUT=$(i3-msg -t get_tree | jq -r '.nodes[] | select([recurse(.nodes[]?, .floating_nodes[]?) | .focused] | any) | .name'
)


for output in "${!OUTPUTS[@]}"
do
    # Exit if output not plugged in
    if [[  " ${CURRENT_OUTPUTS[*]} " != *" ${output} "* ]]; then
        continue
    fi

    # This script switches for all outputs at the same time. If we want to switch for only the focused
    # output, uncomment the following block:
    # if [[ "${FOCUSED_OUTPUT}" != "${output}" ]]; then
    #     break
    # fi

    CURRENT_WORKSPACE=$(i3-msg -t get_workspaces | jq -r --arg output "$output" '.[] | select(.visible and (.output==$output)).name')
    OUTPUT_WORKSPACES=(${OUTPUTS[$output]})
    IS_FOCUSED=$(i3-msg -t get_workspaces | jq -r --arg output "$output" '.[] | select(.visible and (.output==$output)).focused')
    echo $CURRENT_WORKSPACE
    echo $OUTPUT_WORKSPACES
    echo $IS_FOCUSED
    # Get the index of current workspace
    index=-1
    for i in "${!OUTPUT_WORKSPACES[@]}";
    do
        if [[ "${OUTPUT_WORKSPACES[$i]}" = "${CURRENT_WORKSPACE}" ]];
        then
            index=$i
            break
        fi
    done

    # If index is last, then loop over to first
    if [[ "$(expr ${#OUTPUT_WORKSPACES[@]} - 1)" = "${index}" ]];
    then
        NEXT_WORKSPACE="${OUTPUT_WORKSPACES[0]}"
    else
        NEXT_WORKSPACE="${OUTPUT_WORKSPACES[$index+1]}"
    fi

    if [[ "${args[0]}" == "--move" && "${IS_FOCUSED}"=="true" ]]; then
        i3-msg move container to workspace $NEXT_WORKSPACE
    fi
    i3-msg workspace $NEXT_WORKSPACE
done
