#!/bin/bash

source ~/.secrets/credentials.sh

tmpfile=$(mktemp)
flameshot gui -r > $tmpfile
gcloud \
  ml vision detect-text $tmpfile \
  --project="$GCP_PROJECT_FOR_VISION" \
  | jq -r  '.responses[].fullTextAnnotation.text' \
  | xclip -selection clipboard -o
notify-send --expire-time 1500 "OCR copied to clipboard!"
